AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create an S3 bucket with versioning enabled or disabled.

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket.
    Default: mjlab2
  EnableVersioning:
    Type: String
    Description: Enable versioning for the S3 bucket.
    Default: true
    AllowedValues:
      - true
      - false

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !If [IsVersioningEnabled, 'Enabled', 'Suspended']

Conditions:
  IsVersioningEnabled: !Equals [!Ref EnableVersioning, 'true']

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref S3Bucket
  BucketARN:
    Description: ARN of the S3 bucket
    Value: !GetAtt S3Bucket.Arn
  WebsiteURL:
    Description: URL for the S3 bucket website
    Value: !GetAtt S3Bucket.WebsiteURL
    Condition: IsVersioningEnabled